import { CSSProperties } from "react";
export type EnrollmentStyles = Record<string, CSSProperties>;

export const enrollmentStyles: EnrollmentStyles = {
  formSection: {
    flex: "1 1 40%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    marginLeft: "30px",
    marginRight: "30px",
    borderRadius: "12px",
    boxShadow: "0 6px 15px rgba(0, 0, 0, 0.15)",
    opacity: 0,
    transform: "translateY(20px)",
  },
  formCard: {
    width: "100%",
    maxWidth: "400px",
    backgroundColor: "transparent",
    padding: "1.5rem",
    borderRadius: "12px",
    color: "#333",
  },
  input: {
    width: "100%",
    padding: "0.6rem",
    marginBottom: "0.8rem",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#ddd",
    borderRadius: "8px",
    fontSize: "0.8rem",
    transition: "border-color 0.3s ease-in-out",
  },
  inputFocus: {
    borderColor: "#ff6b6b",
  },
  textarea: {
    width: "100%",
    height: "100px",
    padding: "0.6rem",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#ccc",
    borderRadius: "8px",
    fontSize: "0.8rem",
    resize: "vertical",
    marginBottom: "1rem",
    transition: "border-color 0.3s ease-in-out",
  },
  textareaFocus: {
    borderColor: "#ff6b6b",
  },
  formLabel: {
    fontWeight: "bold",
    fontSize: "1.2rem",
    color: "#333",
    textAlign: "center",
    display: "block",
    marginBottom: "0.8rem",
  },
  form: {
    display: "flex",
    flexDirection: "column",
  },
  button: {
    width: "100%",
    padding: "0.6rem",
    backgroundColor: "#ff6b6b",
    color: "#fff",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "1rem",
    fontWeight: "bold",
    transition: "background-color 0.3s ease-in-out, transform 0.2s ease-in-out",
    boxShadow: "0 4px 10px rgba(0, 0, 0, 0.1)",
  },
  select: {
    width: "100%",
    padding: "0.6rem",
    marginBottom: "0.8rem",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#ddd",
    borderRadius: "8px",
    fontSize: "0.8rem",
    transition: "border-color 0.3s ease-in-out",
    backgroundColor: "#fff",
  },
  selectFocus: {
    borderColor: "#ff6b6b",
  },
};
